# Labels for issues and pull-requests.

labels:
  # Statuses
  - name: "evaluating"
    color: f0ad3f
    description: "Applied to all new issues & PRs, someone needs to triage this."
  - name: "stale"
    color: f0ad3f
    description: "There hasn't been any activity on this for quite some time."
  - name: "blocked"
    color: 3732e4
    description: "This is being blocked by other ongoing issues."
  - name: "help-wanted"
    color: 3732e4
    description: "We need some extra helping hands or expertise in order to resolve this."
  - name: "discussion-needed"
    color: 3732e4
    description: "This should be discussed first before proceeding."
  - name: "investigating"
    color: f0ad3f
    description: "This is currently being investigated and looked into."
  - name: "incomplete"
    color: ee0701
    description: "Marks a PR or issue that is missing information."
  - name: "duplicate"
    color: ee0701
    description: "This issue or pull request already exists."
  - name: "wontfix"
    color: ee0701
    description: "This won't be worked on."
  - name: "monitoring"
    color: 2af79e
    description: "This is still being monitored before it can be closed as resolved."

  # Types
  - name: "bug"
    color: 0052cc
    description: "Something isn't working as expected."
  - name: "enhancement"
    color: 0052cc
    description: "Enhancement of the code, not introducing new features."
  - name: "feature"
    color: 0052cc
    description: "New feature, concept idea or suggestion."
  - name: "docs"
    color: 0052cc
    description: "Solely about the documentation of the project."
  - name: "dependencies"
    color: 0052cc
    description: "Upgrade or downgrade of project dependencies."
  - name: "question"
    color: 0052cc
    description: "Further information is requested for discussion."
  - name: "refactor"
    color: 0052cc
    description: "Improvement of existing code."
  - name: "performance"
    color: 0052cc
    description: "Improvement of performance."
  - name: "workflow"
    color: 0052cc
    description: "Improvement of the general workflow."
  - name: "translation"
    color: 0052cc
    description: "Request for better localization."
  - name: "maintenance"
    color: 0052cc
    description: "Generic maintenance tasks."

  # Semantic Versioning
  - name: "major"
    color: 98dae3
    description: "This will cause a major bump in the version X.0.0"
  - name: "minor"
    color: 98dae3
    description: "This will cause a minor bump in the version 0.X.0"
  - name: "patch"
    color: 98dae3
    description: "This will cause a patch bump in the version 0.0.X"

  # Priorities
  - name: "security"
    color: ee0701
    description: "Marks a security issue that needs to be resolved ASAP."
  - name: "critical"
    color: ee0701
    description: "This should be dealt with first. Not fixing this issue might be a serious error."
  - name: "high"
    color: ee0701
    description: "After critical issues are fixed, these should be dealt with before any further issues."
  - name: "medium"
    color: 0e8a16
    description: "This issue may be useful, and needs some attention."
  - name: "low"
    color: 0e8a16
    description: "Nice addition, maybe... someday..."

  # Featuring
  - name: "breaking-changes"
    color: 71241c
    description: "This might break other parts of the code."

  # Special
  - name: "beginner-friendly"
    color: 0e8a16
    description: "Good first issue for people wanting to contribute to the project."
  - name: "no-stale"
    color: f0ad3f
    description: "This is exempted from the stale bot."
