name = "frostproject/roblox_library_template"
description = "A template for Roblox developers to integrate advanced CLI tools like Argon or Rojo into GitHub workflows, streamlining build, test, and deploy processes for libraries and packages."
version = "0.0.5"
authors = ["iceeburr <iceeburr@gmail.com> (https://iceeburr.dev)"]
repository = "https://github.com/frostproject/roblox-library-template"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**/*.luau", "LICENSE"]

[target]
environment = "roblox"
lib = "src/main.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/scripts_argon/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts_argon/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
scripts_argon = { name = "frostproject/scripts_argon", version = "^0.0.3", target = "lune" }
argon = { name = "pesde/argon", version = "^2.0.25", target = "lune" }
